
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Leonard
 */
public class konversi extends javax.swing.JFrame {
    public konversi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Container = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtfield_NIS = new javax.swing.JTextField();
        txtfield_NamaDUDI = new javax.swing.JTextField();
        txtfield_AlamatDUDI = new javax.swing.JTextField();
        txtfield_Durasi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtfield_Nama = new javax.swing.JTextField();
        txtfield_Kelas = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtfield_Kedisiplinan = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtfield_Kepemimpinan = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtfield_KerjaTim = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtfield_Kejuruan = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtfield_Manajerial = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtfield_Rerata = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtfield_Predikat = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtfield_Keterangan = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        btn_Konversi = new javax.swing.JButton();
        btn_IsiLagi = new javax.swing.JButton();
        btn_Keluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Sistem Input Nilai PKL");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("SMKN 8 Semarang");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(233, 233, 233))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(136, 136, 136))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(136, 31));

        jLabel3.setText("Data identitas");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(15, 15, 15))
        );

        jPanel3.setBackground(new java.awt.Color(51, 102, 255));

        jLabel4.setText("NIS :");

        txtfield_NIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfield_NISActionPerformed(evt);
            }
        });
        txtfield_NIS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfield_NISKeyTyped(evt);
            }
        });

        txtfield_NamaDUDI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfield_NamaDUDIActionPerformed(evt);
            }
        });

        txtfield_AlamatDUDI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfield_AlamatDUDIActionPerformed(evt);
            }
        });

        txtfield_Durasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfield_DurasiActionPerformed(evt);
            }
        });
        txtfield_Durasi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfield_DurasiKeyTyped(evt);
            }
        });

        jLabel5.setText("Nama :");

        jLabel6.setText("Kelas :");

        jLabel7.setText("Nama DUDI :");

        jLabel8.setText("Alamat DUDI :");

        jLabel9.setText("Durasi  :");

        jLabel10.setText("Bulan");

        txtfield_Nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfield_NamaActionPerformed(evt);
            }
        });

        txtfield_Kelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "X", "XI", "XII" }));
        txtfield_Kelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfield_KelasActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(51, 51, 255));

        jLabel11.setText("Kepemimpinan :");

        txtfield_Kedisiplinan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfield_KedisiplinanActionPerformed(evt);
            }
        });
        txtfield_Kedisiplinan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfield_KedisiplinanKeyTyped(evt);
            }
        });

        jLabel12.setText("Kedisiplinan :");

        txtfield_Kepemimpinan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfield_KepemimpinanActionPerformed(evt);
            }
        });
        txtfield_Kepemimpinan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfield_KepemimpinanKeyTyped(evt);
            }
        });

        jLabel13.setText("Kerja Tim :");

        txtfield_KerjaTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfield_KerjaTimActionPerformed(evt);
            }
        });
        txtfield_KerjaTim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfield_KerjaTimKeyTyped(evt);
            }
        });

        jLabel14.setText("Kejuruan :");

        txtfield_Kejuruan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfield_KejuruanActionPerformed(evt);
            }
        });
        txtfield_Kejuruan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfield_KejuruanKeyTyped(evt);
            }
        });

        jLabel15.setText("Manajerial :");

        txtfield_Manajerial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfield_ManajerialActionPerformed(evt);
            }
        });
        txtfield_Manajerial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfield_ManajerialKeyTyped(evt);
            }
        });

        jLabel16.setText("Rerata :");

        txtfield_Rerata.setEnabled(false);
        txtfield_Rerata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfield_RerataActionPerformed(evt);
            }
        });

        jLabel17.setText("Predikat :");

        txtfield_Predikat.setEnabled(false);
        txtfield_Predikat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfield_PredikatActionPerformed(evt);
            }
        });

        jLabel18.setText("Keterangan :");

        txtfield_Keterangan.setEnabled(false);
        txtfield_Keterangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfield_KeteranganActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtfield_Kedisiplinan, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfield_Kepemimpinan, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfield_KerjaTim, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfield_Kejuruan, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfield_Manajerial, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfield_Rerata, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfield_Predikat, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfield_Keterangan, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtfield_Kepemimpinan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(txtfield_Kedisiplinan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtfield_KerjaTim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtfield_Kejuruan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtfield_Manajerial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtfield_Rerata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtfield_Predikat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtfield_Keterangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtfield_Kelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtfield_Durasi, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtfield_NIS, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtfield_NamaDUDI, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtfield_AlamatDUDI, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtfield_Nama, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtfield_NIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtfield_Nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtfield_Kelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfield_NamaDUDI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfield_AlamatDUDI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfield_Durasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel5.setBackground(new java.awt.Color(102, 51, 255));

        btn_Konversi.setText("Konversi");
        btn_Konversi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_KonversiActionPerformed(evt);
            }
        });

        btn_IsiLagi.setText("Isi lagi");
        btn_IsiLagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_IsiLagiActionPerformed(evt);
            }
        });

        btn_Keluar.setText("Keluar");
        btn_Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_KeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(btn_Konversi)
                .addGap(141, 141, 141)
                .addComponent(btn_IsiLagi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Keluar)
                .addGap(25, 25, 25))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Konversi)
                    .addComponent(btn_IsiLagi)
                    .addComponent(btn_Keluar))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ContainerLayout = new javax.swing.GroupLayout(Container);
        Container.setLayout(ContainerLayout);
        ContainerLayout.setHorizontalGroup(
            ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        ContainerLayout.setVerticalGroup(
            ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContainerLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jScrollPane1.setViewportView(Container);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtfield_NISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfield_NISActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfield_NISActionPerformed

    private void txtfield_NamaDUDIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfield_NamaDUDIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfield_NamaDUDIActionPerformed

    private void txtfield_AlamatDUDIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfield_AlamatDUDIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfield_AlamatDUDIActionPerformed

    private void txtfield_DurasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfield_DurasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfield_DurasiActionPerformed

    private void txtfield_KedisiplinanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfield_KedisiplinanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfield_KedisiplinanActionPerformed

    private void txtfield_KepemimpinanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfield_KepemimpinanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfield_KepemimpinanActionPerformed

    private void txtfield_KerjaTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfield_KerjaTimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfield_KerjaTimActionPerformed

    private void txtfield_KejuruanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfield_KejuruanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfield_KejuruanActionPerformed

    private void txtfield_ManajerialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfield_ManajerialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfield_ManajerialActionPerformed

    private void txtfield_RerataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfield_RerataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfield_RerataActionPerformed

    private void txtfield_PredikatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfield_PredikatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfield_PredikatActionPerformed

    private void txtfield_KeteranganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfield_KeteranganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfield_KeteranganActionPerformed

    private void btn_IsiLagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_IsiLagiActionPerformed
        txtfield_Nama.setText(null);
        txtfield_NIS.setText(null);
        txtfield_NamaDUDI.setText(null);
        txtfield_AlamatDUDI.setText(null);
        txtfield_Durasi.setText(null);
        txtfield_Kelas.setSelectedItem("Pilih");
        txtfield_Kepemimpinan.setText(null);
        txtfield_Kedisiplinan.setText(null);
        txtfield_KerjaTim.setText(null);
        txtfield_Kejuruan.setText(null);
        txtfield_Manajerial.setText(null);
        txtfield_Rerata.setText(null);
        txtfield_Keterangan.setText(null);
        txtfield_Predikat.setText(null);
    }//GEN-LAST:event_btn_IsiLagiActionPerformed

    private void txtfield_NamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfield_NamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfield_NamaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    private void txtfield_NISKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfield_NISKeyTyped
        harusAngka(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_txtfield_NISKeyTyped

    private void txtfield_DurasiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfield_DurasiKeyTyped
        harusAngka(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_txtfield_DurasiKeyTyped

    private void txtfield_KepemimpinanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfield_KepemimpinanKeyTyped
        harusAngka(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_txtfield_KepemimpinanKeyTyped

    private void txtfield_KedisiplinanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfield_KedisiplinanKeyTyped
        harusAngka(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_txtfield_KedisiplinanKeyTyped

    private void txtfield_KerjaTimKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfield_KerjaTimKeyTyped
        harusAngka(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_txtfield_KerjaTimKeyTyped

    private void txtfield_KejuruanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfield_KejuruanKeyTyped
        harusAngka(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_txtfield_KejuruanKeyTyped

    private void txtfield_ManajerialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfield_ManajerialKeyTyped
        harusAngka(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_txtfield_ManajerialKeyTyped

    private void btn_KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_KeluarActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btn_KeluarActionPerformed

    private void btn_KonversiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_KonversiActionPerformed
        if(txtfield_NIS.getText().equals(null) || 
           txtfield_Nama.getText().equals(null)||
           txtfield_NamaDUDI.getText().equals(null) ||
           txtfield_AlamatDUDI.getText().equals(null) ||
           txtfield_Durasi.getText().equals(null) ||
           txtfield_Kelas.getSelectedItem().equals("Pilih") ||
           txtfield_Kepemimpinan.getText().equals(null) ||
           txtfield_Kedisiplinan.getText().equals(null) ||
           txtfield_KerjaTim.getText().equals(null) ||
           txtfield_Kejuruan.getText().equals(null) ||
           txtfield_Manajerial.getText().equals(null)){
                JOptionPane.showMessageDialog(null, "Tidak boleh ada yang kosong!");
            }
        else{
            int NilaiKepemimpinan = Integer.parseInt(txtfield_Kepemimpinan.getText());
            int NilaiKedisiplinan = Integer.parseInt(txtfield_Kedisiplinan.getText());
            int NilaiKerjaTim = Integer.parseInt(txtfield_KerjaTim.getText());
            int NilaiKejuruan = Integer.parseInt(txtfield_Kejuruan.getText());
            int NilaiManajerial = Integer.parseInt(txtfield_Manajerial.getText());
            
            double hasil = (NilaiKepemimpinan + NilaiKedisiplinan + NilaiKerjaTim + NilaiKejuruan + NilaiManajerial)/5;
            txtfield_Rerata.setText(String.format("%.2f", hasil));
            
            if(hasil >= 91 && hasil <=100){
                txtfield_Predikat.setText("Sangat baik");
                txtfield_Keterangan.setText("Kompeten");
            }
            else if(hasil >= 81 && hasil <= 90){
                txtfield_Predikat.setText("Baik");
                txtfield_Keterangan.setText("Kompeten");
            }
            else if(hasil >= 71 && hasil <= 80){
                txtfield_Predikat.setText("Cukup");
                txtfield_Keterangan.setText("Cukup Kompeten");
            }
            else if(hasil >= 61 && hasil <= 70){
                txtfield_Predikat.setText("Kurang");
                txtfield_Keterangan.setText("Kurang KOmpeten");
            }
            else if(hasil <= 60){
                txtfield_Predikat.setText("Sangat kurang");
                txtfield_Keterangan.setText("Kurang KOmpeten");
            }
            else{
                txtfield_Predikat.setText("isikan 0-100");
                txtfield_Keterangan.setText("Unknown");
            }
        }
    }//GEN-LAST:event_btn_KonversiActionPerformed

    private void txtfield_KelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfield_KelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfield_KelasActionPerformed
    public void harusAngka(java.awt.event.KeyEvent evt){
        char karakter = evt.getKeyChar();
        if(!Character.isDigit(karakter)){
            evt.consume();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(konversi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(konversi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(konversi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(konversi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new konversi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Container;
    private javax.swing.JButton btn_IsiLagi;
    private javax.swing.JButton btn_Keluar;
    private javax.swing.JButton btn_Konversi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtfield_AlamatDUDI;
    private javax.swing.JTextField txtfield_Durasi;
    private javax.swing.JTextField txtfield_Kedisiplinan;
    private javax.swing.JTextField txtfield_Kejuruan;
    private javax.swing.JComboBox<String> txtfield_Kelas;
    private javax.swing.JTextField txtfield_Kepemimpinan;
    private javax.swing.JTextField txtfield_KerjaTim;
    private javax.swing.JTextField txtfield_Keterangan;
    private javax.swing.JTextField txtfield_Manajerial;
    private javax.swing.JTextField txtfield_NIS;
    private javax.swing.JTextField txtfield_Nama;
    private javax.swing.JTextField txtfield_NamaDUDI;
    private javax.swing.JTextField txtfield_Predikat;
    private javax.swing.JTextField txtfield_Rerata;
    // End of variables declaration//GEN-END:variables
}
